// Lucide (desktop) → MaterialCommunityIcons (mobile) name mapping.
// Keep in sync with frontend/src/config/navigation/navigationConfig.ts

export const ICON_MAP: Record<string, string> = {
  FileText: 'file-document-outline',
  Inbox: 'inbox',
  Cloud: 'cloud-outline',
  FolderKanban: 'folder-multiple-outline',
  FileSignature: 'file-sign',
  Rocket: 'rocket-outline',
  ListChecks: 'format-list-checks',
  SquareKanban: 'view-column-outline',
  Vote: 'vote-outline',
  Mail: 'email-outline',
  Calendar: 'calendar-blank-outline',
  MessageSquareText: 'message-text-outline',
  Target: 'target',
  Users: 'account-group-outline',
  Contact: 'card-account-details-outline',
  Package: 'package-variant',
  Wrench: 'wrench-outline',
  TicketCheck: 'ticket-confirmation-outline',
  HardDrive: 'harddisk',
  Monitor: 'monitor',
  MonitorSmartphone: 'monitor-cellphone',
  LayoutGrid: 'view-grid-outline',
  BookMarked: 'book-open-page-variant',
  BarChart3: 'chart-bar',
  ClipboardPen: 'clipboard-edit-outline',
  FileSpreadsheet: 'file-table-outline',
  FileBadge: 'file-certificate-outline',
  ShoppingCart: 'cart-outline',
  ClipboardList: 'clipboard-list-outline',
  PackageCheck: 'package-variant-closed-check',
  Warehouse: 'warehouse',
  PackageSearch: 'package-search',
  Boxes: 'package-variant-closed',
  MapPin: 'map-marker-outline',
  Tags: 'tag-multiple-outline',
  ScanLine: 'barcode-scan',
  ReceiptText: 'receipt-text-outline',
  Receipt: 'receipt',
  CreditCard: 'credit-card-outline',
  PiggyBank: 'piggy-bank-outline',
  Wallet: 'wallet-outline',
  Calculator: 'calculator',
  Palmtree: 'palm-tree',
  Plane: 'airplane',
  CalendarDays: 'calendar-month-outline',
  UserCircle: 'account-circle-outline',
  Car: 'car',
  Settings: 'cog-outline',
  FolderGit2: 'source-branch',
  ShoppingBag: 'shopping-outline',
  Briefcase: 'briefcase-outline',
  Home: 'home-outline',
};

export function mapIcon(lucideName: string): string {
  return ICON_MAP[lucideName] ?? 'view-grid-outline';
}
